
const state = {
  lipstickData: {
    title: '美丽人生 口红',
    bannerUrl: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/big-banner/lipstick.jpg',
    list: [
      {
        id: '1',
        type: 'lipstick',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/lipstick-small/dior-1.jpg',
        brandName: 'Dior/迪奥',
        title: '烈艳蓝金唇膏',
        tags: '滋润 保湿 防水',
        price: '299',
      },
      {
        id: '2',
        type: 'lipstick',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/lipstick-small/chanel.jpg',
        brandName: '香奈儿',
        title: '炫亮魅力唇膏',
        tags: '美美滋润轻盈如丝多色',
        price: '299',
      },
      {
        id: '3',
        type: 'lipstick',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/lipstick-small/estee-1.jpg',
        brandName: 'Estee Lauder/雅诗兰黛',
        title: '倾慕唇膏魅色系列',
        tags: '光感显色科技 双唇浓郁饱满 保色',
        price: '270',
      },
      {
        id: '4',
        type: 'lipstick',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/lipstick-small/dior-2.jpg',
        brandName: '【直营】Christian Dior',
        title: '迪奥粉漾诱惑变色润唇膏',
        tags: '变色口红 3.5g',
        price: '299',
      },
      {
        id: '5',
        type: 'lipstick',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/lipstick-small/estee-2.jpg',
        brandName: 'Estee Lauder/雅诗兰黛',
        title: '雅诗兰黛倾慕唇膏-丝绒系列',
        tags: '气质哑光 柔滑质感 保湿',
        price: '270',
      },
      {
        id: '6',
        type: 'lipstick',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/lipstick-small/lancome-1.jpg',
        brandName: 'Lancome/兰蔻',
        title: '菁纯柔润丝缎唇膏',
        tags: '柔滑丝润 妆效持久',
        price: '270',
      },
      {
        id: '7',
        type: 'lipstick',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/lipstick-small/dior-3.jpg',
        brandName: 'Dior/迪奥',
        title: '粉漾诱惑润唇膏',
        tags: '滋润,保湿,持久,易上色,不易脱色',
        price: '209',
      },
      {
        id: '8',
        type: 'lipstick',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/lipstick-small/carslan.jpg',
        brandName: 'CARSLAN/卡姿兰',
        title: ' 金致胶原美芯唇膏',
        tags: '补湿滋润',
        price: '109',
      },
    ],
  },
  femaleBagData: {
    title: '美丽人生 高跟鞋',
    bannerUrl: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/big-banner/lipstick.jpg',
    list: [
      {
        id: '21',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/1.jpg',
        brandName: '女士韩版百搭简约时尚斜挎包',
        title: '',
        tags: '',
        price: '289',
      },
      {
        id: '22',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/2.jpg',
        brandName: '小包包女2018新款潮韩版百搭斜挎小方',
        title: '',
        tags: '',
        price: '218',
      },
      {
        id: '23',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/3.jpg',
        brandName: '【直营】COACH 蔻驰',
        title: '女士PVC小号手',
        tags: '',
        price: '1298',
      },
      {
        id: '24',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/4.jpg',
        brandName: 'CHARLES＆KEITH',
        title: '单肩包',
        tags: 'CK2-20670',
        price: '399',
      },
      {
        id: '25',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/5.jpg',
        brandName: '韩版个性时尚百搭手提链条少女包',
        title: '',
        tags: '',
        price: '279',
      },
      {
        id: '26',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/6.jpg',
        brandName: '【直营】 COACH 蔻驰 ',
        title: '女士牛皮小号',
        tags: '',
        price: '1058',
      },
      {
        id: '27',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/7.jpg',
        brandName: '朱尔大气真皮时尚头层牛皮女士斜挎包',
        title: '',
        tags: '',
        price: '249',
      },
      {
        id: '28',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/8.jpg',
        brandName: '稻草人复古单肩韩版简约女士斜挎包',
        title: ' ',
        tags: '',
        price: '179',
      },
    ],
  },
  highHeeledData: {
    title: '美丽人生 女包',
    bannerUrl: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/big-banner/lipstick.jpg',
    list: [
      {
        id: '11',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/1.jpg',
        brandName: '女士韩版百搭简约时尚斜挎包',
        title: '',
        tags: '',
        price: '289',
      },
      {
        id: '12',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/2.jpg',
        brandName: '小包包女2018新款潮韩版百搭斜挎小方',
        title: '',
        tags: '',
        price: '218',
      },
      {
        id: '13',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/3.jpg',
        brandName: '【直营】COACH 蔻驰',
        title: '女士PVC小号手',
        tags: '',
        price: '1298',
      },
      {
        id: '14',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/4.jpg',
        brandName: 'CHARLES＆KEITH',
        title: '单肩包',
        tags: 'CK2-20670',
        price: '399',
      },
      {
        id: '15',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/5.jpg',
        brandName: '韩版个性时尚百搭手提链条少女包',
        title: '',
        tags: '',
        price: '279',
      },
      {
        id: '16',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/6.jpg',
        brandName: '【直营】 COACH 蔻驰 ',
        title: '女士牛皮小号',
        tags: '',
        price: '1058',
      },
      {
        id: '17',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/7.jpg',
        brandName: '朱尔大气真皮时尚头层牛皮女士斜挎包',
        title: '',
        tags: '',
        price: '249',
      },
      {
        id: '18',
        type: 'femaleBag',
        url: 'https://raw.githubusercontent.com/liuqiyu/shopping-cart/master/static/images/package-small/8.jpg',
        brandName: '稻草人复古单肩韩版简约女士斜挎包',
        title: ' ',
        tags: '',
        price: '179',
      },
    ],
  },
};

export default {
  state,
};
